# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 15:12
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_success', models.NullBooleanField()),
                ('error_message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_ints_app.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='result',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sum_ints_app.Run'),
        ),
    ]
